# Generated by Django 3.2.6 on 2021-10-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dish',
            table='Dish',
        ),
    ]
